// <auto-generated />
namespace Formula1DataApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class driverteam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(driverteam));
        
        string IMigrationMetadata.Id
        {
            get { return "202202110524436_driver-team"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
