// <auto-generated />
namespace Formula1DataApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emptytest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emptytest));
        
        string IMigrationMetadata.Id
        {
            get { return "202202230839428_emptytest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
